### ISSUE TITLE
Showing nodes over-commitment 

### ISSUE THREAD

**Issue by AmrGanz** [kxr/o-must-gather#1]
This is not an issue rather an idea for adding a couple of options:

- **capacity**: Will loop through cluster nodes and show each one's capacity and allocatable resources

- **utilization**: option to loop through cluster nodes and show if they are overcommitted in terms of CPU and Memory Limits "_I am still looking into how to implement it, as the YAML description of each node does not have this type of info_".

**Comment by kxr** [comment]
The problem here is that in must gather we don't have all the projects/pods running on the cluster. So its not possible to calculate the utilization. However we can show capacity from node yamls. That is a good idea.
