### ISSUE TITLE
IBM CloudPak must-gather confusion

### ISSUE THREAD

**Issue by bostrt** [kxr/o-must-gather#12]
IBM CloudPak support has a must-gather image customers can run. The image results in a directory structure that o-must-gather cannot use but is also confusing as the resulting archive shared with support is called "cp-mustgather". 

Can o-must-gather check if the directory name is "cp-mustgather-*" when running `omg use` and presenting a warning about the archive potentially being incompatible must-gather?

**Comment by bostrt** [comment]
Here is the doc on IBM CloudPak must-gather:

https://www.ibm.com/support/knowledgecenter/SSCSJL_4.1.x/help-mustgather.html
https://www.ibm.com/support/knowledgecenter/SSHKN6/support/must-gather/1.x.x/overview.html#data_modules

**Comment by kxr** [comment]
Hello Robert,
Thank you for reporting this. Would it be, by any chance, possible for you to provide (here or privately) a sample of such cp-must-gather? Its alright if you can't, I will try to look it up my self as well.

**Comment by bostrt** [comment]
Sure thing, I will send it to you privately.

**Comment by kxr** [comment]
Since o-must-gather will not pick up a must-gather directory, unless it finds `namespaces/` and `cluster-scoped-resources/` in there, I think there is no need to add additional logic. If anyone tries to `use` a cp-must-gather, it would fail.
