### ISSUE TITLE
Feature Request: Display warning to user when running omg from inside another must-gather

### ISSUE THREAD

**Issue by bostrt** [kxr/o-must-gather#20]
Users are expected to run `omg use .` when changing must-gather contexts. However, as a user, when looking at multiple (~10-15) different must-gathers throughout a day its easy to forget to change contexts each time. Especially when moving between two must-gathers from the same cluster (or support case). The consequence of not changing contexts without knowing can result in something as simple as embarrassment for reviewing the wrong must-gather or something as critical a using a must-gather from the wrong time-frame of an issue and suggesting a cluster is stable to a customer. 

Would it be feasible to include a warning to the user when they are running an `omg` command outside of the current omg context? 

Lastly, is this request similar enough to https://github.com/kxr/o-must-gather/issues/15 that you can include it in work for that issue?

**Comment by kxr** [comment]
@bostrt  Hey I have added two new features to help solve this problem:

- When run without any arguments i.e, just `omg use`, omg will show you the details of the currently selected must-gather. For example:

        # omg use ./must-gather.local.2723199189299891619
        Now using project "openshift-monitoring" on must-gather "/home/knaeem/Downloads/must-gather.local.2723199189299891619/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-d7c882054a4528eda72e69a7988c5931b5a1643913b11bfd2575a78a8620808f"
    
        # omg use
        Current must-gather: /home/knaeem/Downloads/must-gather.local.2723199189299891619/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-d7c882054a4528eda72e69a7988c5931b5a1643913b11bfd2575a78a8620808f
            Current Project: openshift-monitoring
            Cluster API URL: ['https://api.ocp4.aidemo.local:6443']
           Cluster Platform: ['oVirt']

- To facilitate users working with multiple must-gathers, you can now set the current working directory to be used as the must-gather path. In this case, simply switching the current working directory to the desired must-gather will be enough to start using that must-gather. To use this mode, simply run `omg use --cwd`. For example:

        # omg use --cwd
        Using your current working directory

        # cd /home/knaeem/Downloads/must-gather.local.2723199189299891619/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-d7c882054a4528eda72e69a7988c5931b5a1643913b11bfd2575a78a8620808f

        # omg use
        Current must-gather: .
            Current Project: openshift-monitoring
            Cluster API URL: ['https://api.ocp4.aidemo.local:6443']
           Cluster Platform: ['oVirt']

        # cd /home/knaeem/Downloads/must-gather.local.7890185621691109993/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-549bd48582a9fa615b8728bc6e1d66f3a9c829f415d9ddd58f95eb978be50274

        # omg use
        Current must-gather: .
            Current Project: openshift-monitoring
            Cluster API URL: ['https://api.ocpprod.example.com:6443']
           Cluster Platform: ['None']
