### ISSUE TITLE
Specify 'oc get all,pvc' to return both all and other object types

### ISSUE THREAD

**Issue by kevchu3** [kxr/o-must-gather#21]
From #19 , there were some loose ends on the logic that needs to be tweaked.  Per @kxr, we should be able to specify all with other object types. For example `oc get all,pvc`.  Current logic is only returning the static list of resources defined in `oc get all`.

**Comment by kxr** [comment]
@kevchu3 Thank you for opening this issue. I am already working on this. Will push the changes in a couple of hours.

**Comment by kxr** [comment]
@kevchu3  I have implemented this. See this [commit](https://github.com/kxr/o-must-gather/commit/ec228bfcb6f948c7a0eb39c4fac4763d85814697). Most of what you have done remained intact.

I would appreciate you if you can test it and report any scenario that is not being handled properly.

**Comment by kevchu3** [comment]
@kxr

I ran some tests, it looks like `omg get all,<some other type>` is now mostly returning correct output :)  There were some corner cases that I saw:

* `omg get all,all` returns `[ERROR] Invalid object type:  all`

* `omg get all,co` should actually return clusteroperators with a resource type of `clusteroperator.config.openshift.io` (the part before the /) but instead returns cluster operators with timestamps, such as below:
```
... properly returns the oc get all part ...

NAME                                                           VERSION  AVAILABLE  PROGRESSING  DEGRADED  SINCE
clusteroperator/authentication                                 4.6.4    True       False        False     5d
2020-11-11T19:47:06Z/cloud-credential                          4.6.4    True       False        False     5d
2020-11-11T19:08:31Z/cluster-autoscaler                        4.6.4    True       False        False     5d
2020-07-21T20:50:03Z/config-operator                           4.6.4    True       False        False     28d
2020-07-27T18:22:55Z/console                                   4.6.4    True       False        False     5d
... and more ...
```

However, this case isn't specific to the implementation of all, because `omg get svc,co` would return the same unexpected output for clusteroperators.

* Carrying this a bit further, it doesn't seem to be specific to clusteroperator resource type.  The command `omg get mc,svc` returns `machineconfig/00-master` whereas the oc cli returns `machineconfig.machineconfiguration.openshift.io/00-master` instead.  Close enough, but it might give us some insight into how we can fix the previous corner case.

**Comment by kxr** [comment]
@kevchu3 Thank you for pointing this out. It was my [silly mistake](https://github.com/kxr/o-must-gather/commit/e04093d4fd3a03ed0d743e4a5c5e320f140e6c4c). I was using 't' variable which holding object type, again in the code to store time :|

**Comment by kxr** [comment]
> omg get all,all returns [ERROR] Invalid object type: all

I think this is fine :)

**Comment by kxr** [comment]
> The command omg get mc,svc returns machineconfig/00-master whereas the oc cli returns machineconfig.machineconfiguration.openshift.io/00-master instead. Close enough, but it might give us some insight into how we can fix the previous corner case.

Yes this is a good point. And I think it should be implemented. I will see how it can be achieved.
