### ISSUE TITLE
Shell autocompletion

### ISSUE THREAD

**Issue by bostrt** [kxr/o-must-gather#26]
@kxr I'd like to submit a PR that includes some autocompletion support for o-must-gather. I'm looking at two options:

A. Migrate https://github.com/kxr/o-must-gather/blob/master/omg/cli.py to [Click](https://click.palletsprojects.com/en/7.x/) which has some support built in.
B. I'm also looking at https://kislyuk.github.io/argcomplete/ 

I'm very familiar with Click so am happy to migrate to that, but only if you think its worthwhile. I'm also happy to work in argcomplete (its a one-liner) and then fill in some of the functionality to dynamically autocomplete things like Pod names, Node names, etc. 

WDYT?

**Comment by AmrGanz** [comment]
++

I would love to see this feature in place, I was thinking about it a while ago but didn't invest enough time to have a plan like yours @bostrt

**Comment by kxr** [comment]
@bostrt Yeah that would awesome. I am not happy with argparse. It gets the job done, but can do better. I was planning to look into this. Click looks interesting. Would love to see how it fits. Feel free to send a PR, I would really appreciate that. However I am currently under heavy workload and holiday season is almost here, so I don't mind if you take your time :)

**Comment by bostrt** [comment]
Certainly! I'll submit a pr to get things started

**Comment by bostrt** [comment]
I think this can be closed!
