### ISSUE TITLE
Support for oc adm inspect

### ISSUE THREAD

**Issue by bostrt** [kxr/o-must-gather#32]
I think checking for just the namespaces directory would be enough to include support for `oc adm inspect ns/<name>` captures. 

https://github.com/kxr/o-must-gather/blob/3b80e3bd4ee67bce2a24b19c1341d8db5e1337e8/omg/cmd/use.py#L41-L42

I'm happy to submit a PR.

**Comment by kxr** [comment]
Good idea! Actually I was thinking of the following two ideas along the same lines:

- Often times, we are interested in non openshift/core projects that we are troubleshooting. In that case, it would be useful if we could some how get the must-gather with some additional projects/objects. It is technically possible by running the must-gather with a custom script/image but needs some research and testing. For example (from `oc adm must-gather --help`):
    ```
    # gather information using a specific image, command, and pod-dir
    oc adm must-gather --image=my/image:tag --source-dir=/pod/directory -- myspecial-command.sh
    ```
- When collecting must-gather with multiple images [1] (e.g, service mesh or other components), omg should recognize the must-gathers from multiple images (placed in separate directories) and show combined results.


Anyway, I am working on this and will keep in mind the support for `oc adm inspect`. Let me know if you have any additional thoughts on this.

[1] https://docs.openshift.com/container-platform/4.4/support/gathering-cluster-data.html#gathering-data-specific-features_gathering-cluster-data

**Comment by kxr** [comment]
[Done](https://github.com/kxr/o-must-gather/commit/3b0407fbd5fb21e9d5fe11d5a2c5bf92625e25d6)
