### ISSUE TITLE
Using CSafeLoader over SafeLoader?

### ISSUE THREAD

**Issue by bostrt** [kxr/o-must-gather#33]
YAML CLoader is way faster then the SafeLoader being used right now. Any thoughts on moving to CLoader? I'm not a YAML parsing expert so not sure about the risk. 

```
CLoader:
$ time omg get mc 01-worker-kubelet
NAME               GENERATEDBYCONTROLLER                     IGNITIONVERSION  AGE
01-worker-kubelet  c470febe19e3b004fb99baa6679e7597f50554c5  3.1.0            28d

real	0m0.518s
user	0m0.486s
sys	0m0.032s

---

SafeLoader (current)
$ time omg get mc 01-worker-kubelet
NAME               GENERATEDBYCONTROLLER                     IGNITIONVERSION  AGE
01-worker-kubelet  c470febe19e3b004fb99baa6679e7597f50554c5  3.1.0            28d

real	0m6.822s
user	0m6.795s
sys	0m0.028s
```

**Comment by bostrt** [comment]
I see now that there is actually a `CSafeLoader` in pyyaml so maybe we can consider using it. Its still way faster than the `SafeLoader` which I guess is pure Python and slower.

**Comment by kxr** [comment]
@bostrt Good idea. I will test CSafeLoader and adopt it.

**Comment by bostrt** [comment]
Just a note: A member of the Ansible team advised the use the following for fallback:
```
try:
    # use C version if possible for speedup
    from yaml import CSafeLoader as SafeLoader
except ImportError:
    from yaml import SafeLoader
```

**Comment by kxr** [comment]
@bostrt Done. Thank you for your suggestion. CSafeLoader is definitely a lot faster.
