### ISSUE TITLE
omg use completion

### ISSUE THREAD

**Issue by bostrt** [kxr/o-must-gather#35]
Continuing the conversation from https://github.com/kxr/o-must-gather/pull/29#issuecomment-770231901

Looks like Click might be address this in version 8 but that's still alpha. 

For now, it looks like we'd have to generate the completion scripts and modify them. In other words, make `omg completion ...` so that it echoes out a script we maintain. If my testing is correct for Bash completion, it shouldn't be a big deal. Here's what works for me. The only change was adding `-o default`. I'll submit a PR for this once I test some more. I'll do the same for Fish and Zsh. 

```
_omg_completion() {
    local IFS=$'
'
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   _OMG_COMPLETE=complete $1 ) )

    return 0
}

_omg_completionetup() {
    local COMPLETION_OPTIONS=""
    local BASH_VERSION_ARR=(${BASH_VERSION//./ })
    # Only BASH version 4.4 and later have the nosort option.
    if [ ${BASH_VERSION_ARR[0]} -gt 4 ] || ([ ${BASH_VERSION_ARR[0]} -eq 4 ] && [ ${BASH_VERSION_ARR[1]} -ge 4 ]); then
        COMPLETION_OPTIONS="-o nosort -o default"
    fi
    
    complete $COMPLETION_OPTIONS -F _omg_completion omg
}

_omg_completionetup;
```

**Comment by kxr** [comment]
@bostrt Yeah makes perfect sense. I came to the same conclusion and was planning to study and understand the *_completion* bash functions (I know the gist but don't know them enough to hack). Thank you for this, you saved me a lot of time :). Hopefully with click 8.x it would be simply passing `type=dir` to get this functionality.

**Comment by kxr** [comment]
@bostrt Did you get time to look into this. If you are busy, for now we can fix the bash auto-completion, what do you think?

**Comment by bostrt** [comment]
hey @kxr i haven't been able to look into the fish and zsh solutions, but bash will be easy. I will submit a PR for that.

Would you recommend we keep the fish and zsh completion or remove it for now since `omg use` will not work properly?
