### ISSUE TITLE
list a node with multiple roles

### ISSUE THREAD

**Issue by AmrGanz** [kxr/o-must-gather#5]
# omg get nodes

If there is a node configured with multiple roles "for example: worker,infra", it displays these roles as one word with no separator.

**Comment by kxr** [comment]
@AmrGanz This was fixed quite some time ago. Are you sure on the latest version (currently 0.7). If not do a `pip3 install --upgrade o-must-gather --user`. Or if you are using the code directly then `git pull`.

**Comment by AmrGanz** [comment]
After updating it the behavior is now as expected.
~~~
# pip3 install --upgrade o-must-gather --user
~~~

Closing this one
